default:
  test: false
  selection:
    signal:
      recoil: 250    # min
      leadak4:
        pt: 100   # min
        eta: 2.4  # max
        nhf: 0.8  # max
        chf: 0.1  # min
      leadak8:
        pt: 250   # min
        eta: 2.4  # max
        mass:
          min: 65
          max: 105
        tau21: 0.5 # min
      mindphijr : 0.5 # min
      dpfcalo : 0.5 # max
    control:
      doublemu:
        mass:
          min: 60
          max: 120
      doubleel:
        mass:
          min: 60
          max: 120
      singlemu:
        mt : 160
      singleel:
        mt: 160
  tau:
    cuts:
      pt: 18
      eta: 2.3
  photon:
    cuts:
      loose:
        pt: 15
        eta: 2.5
      tight:
        pt: 175
        eta: 1.4442
    branch:
      id: Photon_cutBasedBitmap
  muon:
    cuts:
      tight:
        pt : 20
        eta : 2.4
        iso : 0.15
      loose:
        pt : 10
        eta : 2.4
        iso : 0.25
  electron:
    cuts:
      tight:
        pt : 40
        eta : 2.5
      loose:
        pt : 10
        eta : 2.5
        dxy: # https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2
          barrel: 0.05
          endcap: 0.10
        dz: # https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2
          barrel: 0.10
          endcap: 0.20
    branch:
      id: Electron_cutBased

  files:
    theory:
      w: data/sf/theory/merged_kfactors_wjets.root
      z: data/sf/theory/merged_kfactors_zjets.root
  run:
    saveevents: True

env:
  test: false

global:
  test: false


era2016:
  triggers:
    met:
      HLT_PFMETNoMu120_PFMHTNoMu120_IDTight
  btag:
    algo: csvv2
    wp: medium
    cuts:
      deepcsv: # https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation2016Legacy
        loose : 0.2217
        medium: 0.6321
        tight: 0.8953
      csvv2:
        loose:  0.5426
        medium: 0.8484
        tight: 0.9535
  electron:
    branch:
      id: Electron_cutBased_Sum16
  sf:
    pileup:
      histogram: "sf2017_nominal"
      file: "data/sf/pileup/pileup.root"
    pileup_up:
      histogram: "sf2017_up"
      file: "data/sf/pileup/pileup.root"
    pileup_down:
      histogram: "sf2017_down"
      file: "data/sf/pileup/pileup.root"

era2017:
  triggers:
    met:
      HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60
  btag:
    algo: deepcsv
    wp: medium
    cuts:
      csvv2: # https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation94X
        loose : 0.5803
        medium : 0.8838
        tight : 0.9693
      deepcsv: # https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation94X
        loose : 0.1522
        medium: 0.4941
        tight: 0.8001
  sf:
    ele_id_loose:
      histogram: EGamma_SF2D
      file: data/sf/egamma/2017_ElectronWPVeto_Fall17V2.root
    ele_id_tight:
      histogram: EGamma_SF2D
      file: data/sf/egamma/2017_ElectronTight.root

    photon_id_tight:
      histogram: EGamma_SF2D
      file: data/sf/egamma/2017_PhotonsMedium.root

    muon_id_loose:
      histogram: NUM_LooseID_DEN_genTracks_pt_abseta
      file: data/sf/muon/2017_RunBCDEF_SF_ID.root
    muon_id_loose_stat:
      histogram: NUM_LooseID_DEN_genTracks_pt_abseta
      file: data/sf/muon/2017_RunBCDEF_SF_ID.root
    muon_id_loose_syst:
      histogram: NUM_LooseID_DEN_genTracks_pt_abseta
      file: data/sf/muon/2017_RunBCDEF_SF_ID.root
    muon_id_tight:
      histogram: NUM_TightID_DEN_genTracks_pt_abseta
      file: data/sf/muon/2017_RunBCDEF_SF_ID.root
    muon_id_tight_stat:
      histogram: NUM_TightID_DEN_genTracks_pt_abseta
      file: data/sf/muon/2017_RunBCDEF_SF_ID.root
    muon_id_tight_syst:
      histogram: NUM_TightID_DEN_genTracks_pt_abseta
      file: data/sf/muon/2017_RunBCDEF_SF_ID.root
    pileup:
      histogram: "sf2017_nominal"
      file: "data/sf/pileup/pileup.root"
    pileup_up:
      histogram: "sf2017_up"
      file: "data/sf/pileup/pileup.root"
    pileup_down:
      histogram: "sf2017_down"
      file: "data/sf/pileup/pileup.root"

era2018:
  triggers:
    met:
      HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60
  btag:
    algo: deepcsv
    wp: medium
    cuts:
      deepcsv: # https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation102X
        loose : 0.1241
        medium: 0.4184
        tight: 0.7527
  sf:
    ele_id_loose:
      histogram: EGamma_SF2D
      file: data/sf/egamma/2018_ElectronWPVeto_Fall17V2.root
    ele_id_tight:
      histogram: EGamma_SF2D
      file: data/sf/egamma/2018_ElectronTight.root
    photon_id_tight:
      histogram: EGamma_SF2D
      file: data/sf/egamma/2018_PhotonsMedium.root
    muon_id_loose:
      histogram: NUM_LooseID_DEN_TrackerMuons_pt_abseta
      file: data/sf/muon/2018_RunABCD_SF_ID.root
    muon_id_loose_stat:
      histogram: NUM_LooseID_DEN_TrackerMuons_pt_abseta_stat
      file: data/sf/muon/2018_RunABCD_SF_ID.root
    muon_id_loose_syst:
      histogram: NUM_LooseID_DEN_TrackerMuons_pt_abseta_syst
      file: data/sf/muon/2018_RunABCD_SF_ID.root
    muon_id_tight:
      histogram: NUM_TightID_DEN_TrackerMuons_pt_abseta
      file: data/sf/muon/2018_RunABCD_SF_ID.root
    muon_id_tight_stat:
      histogram: NUM_TightID_DEN_TrackerMuons_pt_abseta_stat
      file: data/sf/muon/2018_RunABCD_SF_ID.root
    muon_id_tight_syst:
      histogram: NUM_TightID_DEN_TrackerMuons_pt_abseta_syst
      file: data/sf/muon/2018_RunABCD_SF_ID.root
    pileup:
      histogram: "sf2018_nominal"
      file: "data/sf/pileup/pileup.root"
    pileup_up:
      histogram: "sf2018_up"
      file: "data/sf/pileup/pileup.root"
    pileup_down:
      histogram: "sf2018_down"
      file: "data/sf/pileup/pileup.root"
