default:
  test: false
  selection:
    signal:
      recoil: 250    # min
      leadak4:
        pt: 100   # min
        eta: 2.4  # max
        nhf: 0.8  # max
        chf: 0.1  # min
      leadak8:
        pt: 250   # min
        eta: 2.4  # max
        mass:
          min: 65
          max: 105
        tau21: 0.5 # min
      mindphijm : 0.5 # min
      dpfcalo : 0.4 # max
    control:
      doublemu:
        mass:
          min: 60
          max: 120
      doubleel:
        mass:
          min: 60
          max: 120
      singlemu:
        mt : 160
      singleel:
        mt: 160
  tau:
    cuts:
      pt: 18
      eta: 2.4
  photon:
    cuts:
      pt: 15
      eta: 2.4
  muon:
    cuts:
      tight:
        pt : 20
        eta : 2.4
        iso : 0.15
      loose:
        pt : 10
        eta : 2.4
        iso : 0.25
  electron:
    cuts:
      tight:
        pt : 40
        eta : 2.4
      loose:
        pt : 10
        eta : 2.4
env:
  test: false

global:
  test: false


era2016:
  triggers:
    met:
      HLT_PFMETNoMu120_PFMHTNoMu120_IDTight
  btag:
    algo: csvv2
    wp: medium
    cuts:
      deepcsv: # https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation2016Legacy
        loose : 0.2217
        medium: 0.6321
        tight: 0.8953
      csvv2:
        loose:  0.5426
        medium: 0.8484
        tight: 0.9535

era2017:
  triggers:
    met:
      HLT_PFMET170_NotCleaned
  btag:
    algo: deepcsv
    wp: medium
    cuts:
      csvv2: # https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation94X
        loose : 0.5803
        medium : 0.8838
        tight : 0.9693
      deepcsv: # https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation94X
        loose : 0.1522
        medium: 0.4941 
        tight: 0.8001

era2018:
  triggers:
    met:
      HLT_PFMET170_NotCleaned
  btag:
    algo: deepcsv
    wp: medium
    cuts:
      deepcsv: # https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation102X
        loose : 0.1241
        medium: 0.4184
        tight: 0.7527 
  